### ISSUE TITLE
[Bug]: PermissionError: Currently the device (arm_characterization) is NOT OCCUPIED, which is currently in status IDLE #136

### ISSUE THREAD

**Issue by odartsi** [CederGroupHub/alab_management#62]
### Current behavior

 error

### Expected Behavior

no error

### Relevant files/images/logs

Error: User input requested: A unrecoverable error has occurred.
(1) remove samples on powdertransfer_crucible_position
(2) remove all other consumables on filled_vial_rack/2, powdertransfer_crucible_position, powdertransfer_vial_position, cap_position/1, cap_position/2, dispenser_balls/slot, shaker/slot, scale/slot, cappinggripper/slot
The error information is Traceback (most recent call last):
File "C:\Users\Ceder-ALAB\projects\alab_management\alab_management\task_actor.py", line 130, in run_task
result = task.run()
File "C:\Users/Ceder-ALAB/Documents/GitHub/alab_one/src\alab_one\tasks\recover_powder.py", line 152, in run
self.set_up_shaking()
File "C:\Users/Ceder-ALAB/Documents/GitHub/alab_one/src\alab_one\tasks\recover_powder.py", line 432, in set_up_shaking
arm.run_programs(
File "C:\Users\Ceder-ALAB\projects\alab_management\alab_management\device_manager.py", line 68, in call
return self._method_handler(*args, **kwargs)
File "C:\Users\Ceder-ALAB\projects\alab_management\alab_management\device_manager.py", line 355, in call
return f.result()
File "C:\Users\Ceder-ALAB\anaconda3\lib\concurrent\futures_base.py", line 458, in result
return self.__get_result()
File "C:\Users\Ceder-ALAB\anaconda3\lib\concurrent\futures_base.py", line 403, in __get_result
raise self._exception
PermissionError: Currently the device (arm_characterization) is NOT OCCUPIED, which is currently in status IDLE

**Comment by bernardusrendy** [comment]
should be solved by https://github.com/CederGroupHub/alab_management/commit/81c81e01b0133d8f48c454506cfa84da15f262cd

and

https://github.com/CederGroupHub/alab_management/commit/d32b92feaa1acf9f8ea6db45c3d7e464bff5d3f9#diff-603fab04c702be745a88fb6b88a11fb4195b647730c17192e81954b02c49b8ae
(with some of the rollbacks: https://github.com/CederGroupHub/alab_management/commit/2735ebbefb7b81596ba452bf6ad305a7cb9d30ba)
